language: go
sudo: false

go:
  - "1.7"
  - "1.8"
  - "1.9"
  - "1.10"
  - "1.11.6"
  - "1.12"
  - "tip"

before_install:
  - export PATH=$HOME/gopath/bin:$PATH
  - go get github.com/mattn/goveralls

script:
  - go test -race ./...
  - go test -coverprofile=coverage.out ./...
  - goveralls -coverprofile=coverage.out -service=travis-ci -ignore=examples/*/*.go,examples/*/*/*.go,examples/*/*/*/*.go

matrix:
  allow_failures:
   - go: tip

git:
  depth: 10

env:
  - GO111MODULE=on