language: go
sudo: false

go:
  - "1.6"
  - "1.7"
  - "1.8"
  - "1.9"
  - "1.10"
  - "tip"

before_install:
  - export PATH=$HOME/gopath/bin:$PATH
  - go get github.com/mattn/goveralls
  - npm install -g codeclimate-test-reporter

script:
  - go test -race ./...
  - go test -covermode=count -coverprofile=cover.out ./...
  - goveralls -coverprofile=cover.out -service=travis-ci -ignore=examples/*,examples/plugins/*/*
  - codeclimate-test-reporter < cover.out

matrix:
  allow_failures:
   - go: tip

git:
  depth: 10
